- hosts: all
  connection: local
  tasks:
    - name: wait for server to rebuild
      wait_for: host={{ inventory_hostname }} port=22 delay=15 timeout=60

- hosts: all
  vars:
      logfile: '/opt/stack/logs/stack.sh.log'
      branch: 'master'

  tasks:

    - name: install git
      sudo: yes
      apt: name=git state=present

    - name: clone upstream devstack
      git: repo=https://github.com/openstack-dev/devstack.git version="{{ branch }}" dest="~/devstack" accept_hostkey=yes

    - name: create a localrc
      shell: "cp ~/devstack/samples/local.conf ~/devstack/local.conf"

    - name: start stack.sh in a screen
      shell: "screen -S devstack -d -m sh -c 'LOGFILE={{ logfile }} ~/devstack/stack.sh'"

    - name: wait for stack.sh to start
      shell: sleep 3

    - name: watch stack.sh stdout
      shell: "tail -n1 {{ logfile }} && screen -list | grep -q devstack"
      register: finished
      until: finished.rc == 1
      delay: 1
      retries: 6000
      ignore_errors: true

    - name: ensure that stack.sh finished
      shell: 'grep "This is your host ip" {{ logfile }}'
      register: stackresult

    - fail: msg="stack.sh did not complete"
      when: stackresult.rc == 1
